spring.application.name=autotrack
server.port=8080

# MongoDB Atlas - Replace with your connection string
spring.data.mongodb.uri=mongodb+srv://it24100900_db_user:4umPA72BbxDssLIP@cluster1.lewvonz.mongodb.net/?appName=Cluster1
spring.data.mongodb.database=autotrack

# JWT
jwt.secret=AutoTrackSuperSecretKeyForJWT2024MustBe256BitsLongToBeSecure!!
jwt.expiration=86400000

# Email (Gmail SMTP) - Replace with your credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eshanhirunaka03@gmail.com
spring.mail.password=doqx papy czli ghsd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5500,http://127.0.0.1:5500,http://localhost:63342

# Logging
logging.level.com.autotrack=DEBUG
